version: '3.8'

services:
  grt-sys-ecommerce:
    image: ecommerce
    environment:
      - DB_HOST=db                  # Hostname do banco (nome do serviço MySQL)
      - DB_USER=ecommerce_user      # Usuário do banco
      - DB_PASSWORD=ecommerce_password  # Senha do usuário
      - DB_NAME=ecommerce_db        # Nome do banco de dados
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: ecommerce-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_password
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
